// --- CONFIGURACIÓN GLOBAL DEL TOKEN ($THND) ---
const TOKEN_DATA = {
    contractAddress: "0x54BF9EcF6b09E86DE19688E636a0368cc8844020",
    ponsUrl: "https://ponsfamily.com"
};

// --- DICCIONARIO DE TRADUCCIONES MAESTRO CORREGIDO ---
const translations = {
    es: {
        titulo_hero: "🏴‍☠️ Tender Parakeet ($THND) 🦜",
        desc_hero: "El pirata más tierno del mar cripto navega con sus alas bien abiertas por la <strong>Robinhoodchain</strong>. ¡Zarpamos desde América en una red de bloques para conquistar el botín de la blockchain con el token <strong>$THND</strong>!",
        btn_copy: "Copiar CA ($THND)",
        btn_buy: "TORMENTA MARINA EN PONS",
        btn_tg_text: "ÁRBOL EN TELEGRAM",
        btn_x_text: "NIDO EN X",
        progress_title: "📈 Progreso del Botín (Curva de Vinculación)",
        progress_desc: "Meta para la graduación y listado automático en Uniswap:",
        progress_loading: "Conectando con el radar de Pons...",
        progress_meta_prefix: "Meta:",
        remaining_text: "Faltan",
        remaining_end: "para Uniswap",
        manifesto_phrase_title: "👑 El Decreto del Nuevo Rey",
        manifesto_phrase_text: '"El tiempo de los no voladores está terminando... ¡Un nuevo rey prepara su nido para conquistar absolutamente toda la blockchain!"',
        buy_steps_title: "🗺️ Abordaje Express (3 Clics)",
        step_1_title: "⚓ Wallet Segura",
        step_1_desc: "Sugerimos crear una <strong>billetera nueva</strong> en MetaMask/Rabby exclusiva para esta preventa. ¡Al listarse en Uniswap podrás migrar tu botín a tu wallet principal!",
        step_2_title: "🪙 Carga Munición",
        step_2_desc: "Asegúrate de tener <strong>$ETH</strong> listo para cambiar por el tesoro.",
        step_3_title: "🦜 ¡Fuego!",
        step_3_desc: "¡Haz clic abajo, ve a <strong>Pons</strong> e intercambia tu botín!",
        btn_buy_now_step: "IR A PONS DIRECTO 🚀",
        tok_title: "🪙 Manifiesto del Botín (Tokenomics)",
        tok_1_title: "👥 100% Comunidad",
        tok_1_desc: "Suministro fijo de 1,000,000,000 $THND. Cero allocations de equipo. Todo inyectado a la curva desde el primer segundo.",
        tok_2_title: "⚔️ 3% Creator Tax & Quema",
        tok_2_desc: "¡Obra Maestra! El 3% financia la flota, pero al listarse en Uniswap, el 50% de todas las comisiones logradas se QUEMARÁ perpetuamente como tributo a tu esfuerzo.",
        tok_3_title: "🌊 Especulación Pura",
        tok_3_desc: "Sin hojas de ruta complejas ni utilidades artificiales. Diseñado estrictamente para entretenimiento en Robinhood Chain.",
        road_title: "🗺️ Nuestro Camino (Roadmap Real)",
        road_intro: "Sin falsas promesas ni utilidades artificiales. Tres pasos claros hacia la descentralización absoluta en Robinhood Chain.",
        road_p1_title: "🐣 Fase 1: El Despegue",
        road_p1_desc: "Diseño de la identidad del Capitán Perico, despliegue del contrato inteligente (CA) y lanzamiento del portal web oficial.",
        road_p2_title: "🪙 Fase 2: Preventa en Pons",
        road_p2_desc: "Apertura oficial de la curva de vinculación (bonding curve) en Pons Launchpad. El 100% del suministro se inyecta directamente al mercado.",
        road_p3_title: "🦅 Fase 3: Uniswap y Gran Quema",
        road_p3_desc: "Al completarse la curva de 4.2 ETH, la liquidez se bloquea perpetuamente. En ese instante, el 50% de las comisiones del creador se envían a la dirección muerta para disparar la escasez del token.",
        status_done: "COMPLETADO ✅",
        status_active: "EN VIVO 🚀",
        status_future: "OBRA MAESTRA PRÓXIMAMENTE 🔥",
        rivals_title: "🦅 El Vuelo frente a los Caminantes de Tierra",
        rivals_intro: "Mientras el resto del mercado cripto se arrastra en la lentitud de los suelos tradicionales, el Capitán Perico despliega sus alas directas al cofre dorado.",
        rival_1_title: "🐸 Saltarines Terrestres",
        rival_1_desc: "Anfibios atrapados en charcos antiguos. Intentan saltar alto usando el viejo meta, pero operan en cámara lenta comparados con nuestro vuelo.",
        rival_2_title: "🐶 Cachorros del Suelo",
        rival_2_desc: "Caninos que ladran en la tierra firme esperando una recompensa que nunca llega. Tienen el piso dominado, pero carecen de la perspectiva que otorga el cielo.",
        rival_3_title: "🐧 Aves sin Alas",
        rival_3_desc: "Observan desde sus islas de hielo cómo se escapa el verdadero botín digital. Tienen plumas, pero olvidaron el arte de volar alto hacia la descentralización.",
        shield_title: "🛡️ El Escudo de Alta Mar (Seguridad Absoluta)",
        shield_intro: "Con la verdad por delante. En este barco protegemos la ética cripto con reglas inquebrantables:",
        shield_b1: "<strong>Cero Datos:</strong> No pedimos, ni procesamos, ni almacenamos ninguna información personal. Tu privacidad es sagrada en alta mar.",
        shield_b2: "<strong>Sin Pagos Ocultos:</strong> Nunca te solicitaremos fondos de desbloqueo, comisiones ocultas ni productos por ningún medio. No existen ni habrá planes de ello.",
        shield_b3: "<strong>Frase Semilla Sagrada:</strong> Jamás te pediremos tus llaves privadas o frases semilla. Ningún desarrollador legítimo te contactará para solicitar pagos.",
        shield_b4: "<strong>Cero Custodia:</strong> No tenemos acceso a tu billetera. Solo tú sabes cuánto tienes, cuándo compras y cuándo decides vender tu botín.",
        shield_b5: "<strong>Contrato Irrevocable:</strong> Al completarse la curva de vinculación, los fondos se bloquean perpetuamente y Pons lista el token en Uniswap de forma inmediata. Nosotros no tenemos tokens ni poder para retenerlos.",
        faq_main_title: "❓ Interrogatorios en el Puerto (FAQ)",
        faq_main_intro: "Todo lo que la tripulación necesita saber antes de abordar la tormenta cripto.",
        faq_q1: "¿En qué red opera el Capitán Perico?",
        faq_a1: "Operamos exclusivamente en la <strong>Robinhood Chain</strong>. Necesitas configurar esta red en tu billetera Web3 e ingresar fondos en $ETH para poder comprar tu botín.",
        faq_q2: "¿El equipo tiene tokens guardados?",
        faq_a2: "<strong>¡Cero tokens para el equipo!</strong> Cumplimos con la ética de un Fair Launch absoluto. El 100% del suministro se inyecta directamente en la curva de vinculación de Pons.",
        faq_q3: "¿Qué es el impuesto del 3% (Creator Tax)?",
        faq_a3: "Es un código inalterable en el contrato. El 3% de cada transacción se destina de forma automática a financiar las campañas de marketing global y el mantenimiento de la flota.",
        faq_q4: "¿Qué pasa cuando la curva llega al 100%?",
        faq_a4: "Ocurre la <strong>Graduación Automática</strong>. La plataforma Pons migra toda la liquidez recolectada hacia Uniswap y quema las llaves de propiedad perpetuamente. ¡Cero Rug-pulls!",
        faq_q5: "¿Pueden robarse los fondos o hacer un Rug-pull?",
        faq_a5: "¡Ni en los peores mitos marinos! No controlamos las monedas de la preventa ni el dinero acumulado. Todo está amarrado al contrato de <strong>Pons Launchpad</strong> de forma automatizada. No hay preventas ocultas ni accesos traseros para vaciar el nido.",
        faq_q6: "¿Por qué insisten tanto en usar una billetera de preventas?",
        faq_a6: "¡Regla de oro de los piratas listos! Usar una <strong>billetera secundaria vacía (Burner Wallet)</strong> es la mejor forma de explorar nuevas dApps de manera segura. Al llegar a la meta de 4.2 ETH y listarse en Uniswap, podrás mudar todo tu tesoro a tu bóveda principal de forma transparente.",
        faq_q7: "¿Cómo sé que el 3% de impuesto se usa bien?",
        faq_a7: "Porque el código no miente. El impuesto está programado directo en la blockchain y se destina por completo a reventar las redes con marketing degen y pagar los servidores de la flota. Nosotros no compramos ni vendemos tokens por la espalda.",
        faq_q8: "¿Cuánto tiempo tardará en listarse en Uniswap?",
        faq_a8: "El tiempo lo decide el viento y la tripulación. La curva se gradúa en el instante exacto en que se llega a la meta de <strong>4.2 ETH</strong>. Puede tardar un día, una semana o unas horas. ¡Tú manejas el ritmo del abordaje!",
        chart_title: "📊 Distribución Científica del Suministro",
        c_1: "Preventa en Pons",
        c_2: "Preventa en Pons (otra vez)",
        c_3: "Saqueo en Pons",
        c_4: "Fondo de Curva Pons",
        c_5: "Botín Exclusivo Pons",
        chart_note: "⚠️ Nota técnica: Gráfico certificado por el Capitán Perico. Cero tokens para el equipo.",
        partner_label: "PROYECTO VERIFICADO EN",
        warning_title: "⚠️ Advertencia de Navegación:"
    },
    en: {
        titulo_hero: "🏴‍☠️ Tender Parakeet ($THND) 🦜",
        desc_hero: "The cutest pirate in the crypto sea sails with his wings wide open through the <strong>Robinhoodchain</strong>. We set sail from America on a blockchain network to conquer the bounty with the <strong>$THND</strong> token!",
        btn_copy: "Copy CA ($THND)",
        btn_buy: "SEA STORM ON PONS",
        btn_tg_text: "TREE ON TELEGRAM",
        btn_x_text: "NEST ON X",
        progress_title: "📈 Bounty Progress (Bonding Curve)",
        progress_desc: "Target for graduation and automatic listing on Uniswap:",
        progress_loading: "Connecting with Pons radar...",
        progress_meta_prefix: "Target:",
        remaining_text: "Missing",
        remaining_end: "to Uniswap",
        manifesto_phrase_title: "👑 The Decree of the New King",
        manifesto_phrase_text: '"The time of the non-flyers is ending... A new king prepares his nest to conquer absolutely the entire blockchain!"',
        buy_steps_title: "🗺️ Express Boarding (3 Clicks)",
        step_1_title: "⚓ Secure Wallet",
