// --- CONFIGURACIÓN GLOBAL DE LA MEMECOIN ---
const TOKEN_DATA = {
    contractAddress: "0x54BF9EcF6b09E86DE19688E636a0368cc8844020",
    ponsUrl: "https://www.ponsfamily.com/launchpad/0x54BF9EcF6b09E86DE19688E636a0368cc8844020",
    twitterUrl: "https://x.com/LinguaMemeCoin",
    telegramUrl: "https://t.me/TenderParakeetOficial"
// --- DICCIONARIO DE TRADUCCIONES COMPLETO ---
const translations = {
    es: {
        hero_title: "🏴‍☠️ Perico Tierno ($THND) 🦜",
        hero_tagline: "El perico más tierno del mar cripto navega con sus alas abiertas por la <strong>Robinhoodchain</strong>. ¡Zarpamos desde América en una red de bloques para conquistar el botín de la blockchain con el token <strong>$THND</strong>!",
        btn_copy: "Copiar CA ($THND)",
        btn_buy: "¡ABORDAR EL BOTÍN!",
        btn_tg_text: "SURCAR EL MAR DIGITAL",
        btn_x_text: "NIDO DEL REY PERICO",
        progress_title: "📈 Progreso del Botín (Curva de Vinculación)",
        progress_desc: "Meta para la graduación y listado automático en Uniswap:",
        progress_loading: "Conectando con el radar de Pons...",
        progress_meta: "Meta: Completar la Curva 🚀",
        manifesto_phrase_title: "👑 El Decreto del Nuevo Rey",
        manifesto_phrase_text: '"El tiempo de los no voladores está terminando... ¡Un nuevo rey prepara su nido para conquistar absolutamente toda la blockchain!"',
        buy_steps_title: "🗺️ Mapa de Abordaje (¿Cómo Comprar?)",
        step_1_title: "⚓ Prepara tu Billetera",
        step_1_desc: "Descarga una billetera compatible con Web3 (como MetaMask o Rabby) y conéctala a la red <strong>Robinhood Chain</strong>.",
        step_2_title: "🪙 Consigue Munición ($ETH)",
        step_2_desc: "Asegúrate de tener Ethereum ($ETH) en la Robinhood Chain en tu billetera para poder intercambiarlo por el botín.",
        step_3_title: "🦜 Reclama tus $THND",
        step_3_desc: "Haz clic en el botón de compra para ir a la plataforma oficial de <strong>Pons</strong>. Conecta tu billetera e intercambia tu ETH.",
        rivals_title: "🦅 El Vuelo frente a los Caminantes de Tierra",
        rivals_intro: "Mientras el resto del mercado cripto se arrastra en la lentitud de los suelos tradicionales, el Capitán Perico despliega sus alas directas al cofre dorado.",
        rival_1_title: "🐸 Saltarines Terrestres",
        rival_1_desc: "Anfibios atrapados en charcos antiguos. Intentan saltar alto usando el viejo meta, pero operan en cámara lenta comparados con nuestro vuelo.",
        rival_2_title: "🐶 Cachorros del Suelo",
        rival_2_desc: "Caninos que ladran en la tierra firme esperando una recompensa que nunca llega. Tienen el piso dominado, pero carecen de la perspectiva que otorga el cielo.",
        rival_3_title: "🐧 Aves sin Alas",
        rival_3_desc: "Observan desde sus islas de hielo cómo se escapa el verdadero botín digital. Tienen plumas, pero olvidaron el arte de volar alto hacia la descentralización.",
        tok_title: "🪙 Manifiesto del Botín (Tokenomics)",
        tok_1_title: "💎 100% Para la Tripulación",
        tok_1_desc: "Transparencia absoluta de alta mar. Los desarrolladores no tenemos tokens asignados. El 100% del suministro se añade a la curva desde el lanzamiento.",
        tok_2_title_text: "3% de Impuesto de Abordaje",
        tok_2_desc: "Cada movimiento en el océano financia la conquista. Existe un 3% de impuesto (creator tax) destinado exclusivamente al marketing y mantenimiento de la flota.",
        tok_3_title: "🌊 Especulación Pura",
        tok_3_desc: "Aquí no hay falsas promesas ni utilidades artificiales. Esta moneda es 100% comunitaria y de entretenimiento. Cero hojas de ruta complicadas.",
        warning_text: "⚠️ Advertencia de Navegación: Al ser un token puramente especulativo y sin utilidad, navegas bajo tu propio riesgo. ¡Asegúrate de arriesgar solo el botín que estés dispuesto a perder en la tormenta (máximo sugerido por la comunidad: $15 USD)!"
    },
    en: {
        hero_title: "🏴‍☠️ Captain Parakeet ($THND) 🦜",
        hero_tagline: "The cutest pirate in the crypto sea sails with wide-open wings through the <strong>Robinhoodchain</strong>. We set sail from America on a block network to conquer the final blockchain bounty with the <strong>$THND</strong> token!",
        btn_copy: "Copy CA ($THND)",
        btn_buy: "PLUNDER THE LOOT!",
        btn_tg_text: "SAIL THE DIGITAL SEA",
        btn_x_text: "KING PARAKEET'S NEST",
        progress_title: "📈 Bounty Progress (Bonding Curve)",
        progress_desc: "Target for graduation and automatic listing on Uniswap:",
        progress_loading: "Connecting to Pons radar...",
        progress_meta: "Goal: Complete the Curve 🚀",
        manifesto_phrase_title: "👑 The Decree of the New King",
        manifesto_phrase_text: '"The time of the non-flyers is coming to an end... A new king prepares his nest to completely conquer the blockchain!"',
        buy_steps_title: "🗺️ Boarding Map (How to Buy?)",
        step_1_title: "⚓ Setup Your Wallet",
        step_1_desc: "Download a Web3 compatible wallet (like MetaMask or Rabby) and connect it to the <strong>Robinhood Chain</strong> network.",
        step_2_title: "🪙 Load Ammo ($ETH)",
        step_2_desc: "Make sure you hold Ethereum ($ETH) bridged into the Robinhood Chain in your wallet to trade for the treasure.",
        step_3_title: "🦜 Claim your $THND",
        step_3_desc: "Click our buy button to go straight to the official <strong>Pons</strong> platform. Connect your wallet and trade your ETH.",
        rivals_title: "🦅 The Flight vs. The Ground Walkers",
        rivals_intro: "While the rest of the crypto market crawls on traditional ground levels, Captain Parakeet spreads his wings straight toward the golden chest.",
        rival_1_title: "🐸 The Earth Leapers",
        rival_1_desc: "Amphibians trapped in old puddles. Trying to jump high using the old meta, but operating in slow motion compared to our flight.",
        rival_2_title: "🐶 Ground Puppies",
        rival_2_desc: "Canines barking on solid ground waiting for a reward that never comes. They rule the floor but lack the sky.",
        rival_3_title: "🐧 Wingless Birds",
        rival_3_desc: "Watching from ice islands as the real digital treasure slips away. They have feathers but forgot how to fly high.",
        tok_title: "🪙 Bounty Manifesto (Tokenomics)",
        tok_1_title: "💎 100% For the Crew",
        tok_1_desc: "Absolute transparency. Developers hold zero team tokens. 100% of supply goes straight to the curve at launch.",
        tok_2_title_text: "3% Boarding Tax",
        tok_2_desc: "Every single move funds the conquest. A 3% creator tax is entirely allocated to aggressive marketing and ship maintenance.",
        tok_3_title: "🌊 Pure Speculation",
        tok_3_desc: "No false promises or fake utilities. This token is 100% community-driven and for entertainment purposes only.",
        warning_text: "⚠️ Navigation Warning: As a purely speculative token with no utility, you sail at your own risk. Only risk what you are willing to lose in the storm (community suggested max: $15 USD)!"
    },
    pt: {
        hero_title: "🏴‍☠️ Capitão Periquito ($THND) 🦜",
        hero_tagline: "O pirata mais fofo dos mares cripto navega de asas abertas pela <strong>Robinhoodchain</strong>. Partimos da América em uma rede de blocos para conquistar o saque final da blockchain com o token <strong>$THND</strong>!",
        btn_copy: "Copiar CA ($THND)",
        btn_buy: "SAQUEAR O BAÚ!",
        btn_tg_text: "NAVEGAR NO MAR DIGITAL",
        btn_x_text: "NINHO DO REI PERIQUITO",
        progress_title: "📈 Progresso do Saque (Curva de Vinculação)",
        progress_desc: "Meta para graduação e listagem automática na Uniswap:",
        progress_loading: "Conectando ao radar do Pons...",
        progress_meta: "Meta: Completar a Curva 🚀",
        manifesto_phrase_title: "👑 O Decreto do Novo Rei",
        manifesto_phrase_text: '"O tempo dos não-voadores está chegando ao fim... Um novo rei prepara seu ninho para conquistar absolutamente toda a blockchain!"',
        buy_steps_title: "🗺️ Mapa de Abordagem (Como Comprar?)",
        step_1_title: "⚓ Prepare sua Carteira",
        step_1_desc: "Baixe uma carteira compatível com Web3 (como MetaMask ou Rabby) e conecte-a à rede <strong>Robinhood Chain</strong>.",
        step_2_title: "🪙 Consiga Munição ($ETH)",
        step_2_desc: "Certifique-se de ter Ethereum ($ETH) na Robinhood Chain na sua carteira para poder trocar pelo saque.",
        step_3_title: "🦜 Reclame seus $THND",
        step_3_desc: "Clique no botão de compra para ir à plataforma oficial do <strong>Pons</strong>. Conecte sua carteira e troque seu ETH.",
        rivals_title: "🦅 O Voo contra os Caminhantes da Terra",
        rivals_intro: "Enquanto o resto do mercado cripto se arrasta nos solos tradicionais, o Capitão Periquito abre suas asas rumo ao baú de ouro.",
        rival_1_title: "🐸 Os Saltadores Terrestres",
        rival_1_desc: "Anfíbios preso em lagoas antigas. Tentam pular alto usando o meta antigo, mas operam em câmera lenta comparados ao nosso voo.",
        rival_2_title: "🐶 Filhotes do Chão",
        rival_2_desc: "Caninos latindo na terra firme esperando uma recompensa que nunca chega. Dominam o piso, mas não conhecem o céu.",
        rival_3_title: "🐧 Aves Sem Asas",
        rival_3_desc: "Observam de suas ilhas de gelo o verdadeiro tesouro digital escapar. Têm penas, mas esqueceram como voar alto.",
        tok_title: "🪙 Manifesto do Saque (Tokenomics)",
        tok_1_title: "💎 100% Para a Tripulação",
        tok_1_desc: "Transparência total. Desenvolvedores têm zero tokens alocados. 100% do suprimento vai para a curva no lançamento.",
        tok_2_title_text: "Taxa de Abordagem de 3%",
